// Protocol v0.2 adoption tests: shared parser / JCS / digest / seal / suite-binding / lock vectors, domain isolation,
// exit codes, peer-index fixtures. Vectors live in test/golden/v0.2 (generated by an independent Python implementation, see generate.py).
import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { spawnSync, execFileSync } from "node:child_process";
import YAML from "yaml";
import {
  PKG_ROOT, DIGEST_ALGORITHM, DataRejectedError, canonicalize, sha256, artifactDigest, suiteDigest, sealPayload, checkSuiteBinding, parseYaml, parseManifestBytes,
  resolveRef, buildRuntimeLock, buildIndex, validateAll, schemaErrors, compareCodePoints, compareUtf16, loadPeerIndexes,
} from "../scripts/lib/core.mjs";

const V = (n) => JSON.parse(fs.readFileSync(path.join(PKG_ROOT, "test/golden/v0.2", n), "utf8"));
const ystr = (v) => YAML.stringify(v, { aliasDuplicateObjects: false });
const SYN = "synthetic/qbs/synthetic.";
const CANON = `${SYN}research-synthesis/1.0.0`, CAND = `${SYN}research-synthesis/1.1.0`, DRAFT = `${SYN}incident-triage/0.1.0`;
const codes = (r) => r.errors.map((e) => e.code);

function sandbox() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "qbv02-"));
  fs.cpSync(path.join(PKG_ROOT, "synthetic"), path.join(root, "synthetic"), { recursive: true });
  fs.mkdirSync(path.join(root, "qbs"));
  return root;
}
const read = (root, rel) => fs.readFileSync(path.join(root, rel), "utf8");
const write = (root, rel, text) => { fs.mkdirSync(path.dirname(path.join(root, rel)), { recursive: true }); fs.writeFileSync(path.join(root, rel), text); };
const mutate = (root, rel, fn) => { const d = YAML.parse(read(root, rel)); fn(d); write(root, rel, ystr(d)); };
/** A full copy of the package (scripts, schemas, registry data) so CLI scripts can be run against a mutated registry. */
function pkgCopy() {
  const root = sandbox();
  for (const f of ["scripts", "schemas", "registries.yaml", "package.json"]) fs.cpSync(path.join(PKG_ROOT, f), path.join(root, f), { recursive: true });
  fs.symlinkSync(path.join(PKG_ROOT, "node_modules"), path.join(root, "node_modules"));
  return root;
}
const cli = (root, script, ...args) => spawnSync(process.execPath, [path.join(root, "scripts", script), ...args], { cwd: root, encoding: "utf8" });

/* ------------------------------------------------------------------ 1. shared parser vectors */
test("v0.2 parser vectors: JSON-compatible YAML subset (text)", () => {
  for (const c of V("parser.json").text) {
    if (c.expect === "ok") { assert.deepEqual(parseYaml(c.yaml), c.value, c.name); continue; }
    let err; try { parseYaml(c.yaml); } catch (e) { err = e; }
    assert.ok(err instanceof DataRejectedError, `${c.name}: expected a controlled rejection, got ${err?.constructor?.name}`);
    assert.ok(err.diagnostics.some((d) => d.code === c.code && (c.path === undefined || d.path === c.path)), `${c.name}: expected ${c.code}${c.path ? ` at ${c.path}` : ""}, got ${JSON.stringify(err.diagnostics)}`);
  }
});
test("v0.2 parser vectors: invalid UTF-8, BOM, NUL, CR are rejected with controlled diagnostics (bytes)", () => {
  for (const c of V("parser.json").bytes) {
    let err; try { parseManifestBytes(Buffer.from(c.bytesHex, "hex")); } catch (e) { err = e; }
    assert.ok(err instanceof DataRejectedError, c.name);
    assert.ok(err.diagnostics.some((d) => d.code === c.code), `${c.name}: ${JSON.stringify(err.diagnostics)}`);
  }
  assert.deepEqual(parseManifestBytes(Buffer.from("a: 1\n")), { a: 1 });
});
test("v0.2 parser: the same rules apply to every registry file through the loader (controlled file/path diagnostics, no crash)", () => {
  const cases = [
    [`${CAND}/blueprint.yaml`, "a: 1\na: 2\n", "E_DUPLICATE_KEY"], [`${CAND}/evals/suite.yaml`, "a: &x 1\nb: *x\n", "E_YAML_ALIAS"],
    [`${CAND}/evidence/refs.yaml`, "m:\n  <<: {a: 1}\n", "E_YAML_MERGE"], [`${CANON}/lifecycle.yaml`, "a: 1\n---\nb: 2\n", "E_YAML_MULTIDOC"],
    [`${CANON}/release.yaml`, "a: 9007199254740993\n", "E_UNSAFE_INTEGER"], [`${CAND}/blueprint.yaml`, "a: .nan\n", "E_DATA_TYPE"],
    [`${CAND}/evals/suite.yaml`, "s: \"\\ud800\"\n", "E_DATA_TYPE"],
  ];
  for (const [rel, text, code] of cases) {
    const root = sandbox();
    write(root, rel, text);
    const r = validateAll({ root });
    assert.ok(r.errors.some((e) => e.code === code && e.file.endsWith(rel.replace(SYN, "").split("/").slice(-1)[0] === "suite.yaml" ? "evals/suite.yaml" : rel.split("/").slice(-1)[0]) || (e.code === code && e.file === rel)), `${rel} ${code}: ${JSON.stringify(r.errors.slice(0, 3))}`);
    assert.ok(!codes(r).includes("E_INTERNAL"), `${rel}: no uncaught exception`);
  }
  for (const [name, bytes, code] of [["BOM", Buffer.concat([Buffer.from([0xef, 0xbb, 0xbf]), fs.readFileSync(path.join(PKG_ROOT, CAND, "blueprint.yaml"))]), "E_ENCODING"], ["NUL", Buffer.from("a: 1\0\n"), "E_BINARY"], ["invalid UTF-8", Buffer.from([0x61, 0x3a, 0x20, 0xff, 0x0a]), "E_ENCODING"], ["CRLF", Buffer.from("a: 1\r\n"), "E_LINE_ENDING"]]) {
    const root = sandbox();
    fs.writeFileSync(path.join(root, CAND, "evals/suite.yaml"), bytes);
    const r = validateAll({ root });
    assert.ok(r.errors.some((e) => e.code === code && e.file.endsWith("evals/suite.yaml")), name);
  }
});

/* ------------------------------------------------------------------ 2. RFC 8785 JCS vectors */
test("v0.2 JCS vectors (independent Python implementation): UTF-16 key order, ES numbers, escaping, no normalisation, no line-ending rewrite", () => {
  const { vectors } = V("jcs.json");
  assert.ok(vectors.length >= 9);
  for (const v of vectors) {
    // numbers that do not fit a JS integer keep their literal via JSON.parse double rounding, exactly like the reference
    const c = canonicalize(JSON.parse(v.inputJson));
    assert.equal(c, v.canonical, v.name);
    assert.equal(sha256(c), v.sha256, v.name);
  }
});
test("v0.2 JCS: rejection vectors (non-finite, lone surrogates, unsupported) throw DataRejectedError and never become null", () => {
  const values = { nan: NaN, infinity: Infinity, "-infinity": -Infinity, "lone-surrogate": "\ud800", unsupported: undefined };
  for (const r of V("jcs.json").rejections) {
    const input = r.kind === "lone-surrogate-key" ? { ["\udc00"]: 1 } : { x: values[r.kind] };
    assert.throws(() => canonicalize(input), DataRejectedError, r.name);
    assert.throws(() => artifactDigest({ metadata: {}, spec: input }), DataRejectedError, r.name);
    assert.throws(() => suiteDigest(input), DataRejectedError, r.name);
  }
});
test("v0.2 ordering: JSON keys use UTF-16 code units (JCS); indexes and paths use code points", () => {
  const astral = "\u{10000}", bmp = "\uffff";
  assert.equal(compareUtf16(astral, bmp), -1, "UTF-16: U+10000 (D800 DC00) sorts before U+FFFF");
  assert.equal(compareCodePoints(astral, bmp), 1, "code point: U+10000 sorts after U+FFFF");
  assert.equal(canonicalize({ [bmp]: 1, [astral]: 2 }), `{"${astral}":2,"${bmp}":1}`);
  const entry = (id) => ({ scope: "synthetic", blueprint: { metadata: { id, version: "1.0.0", maturity: "candidate", lifecycle: "active", origin: { type: "native" } }, references: [], spec: { compatibility: {} } }, digest: "sha256:" + "0".repeat(64), errors: [], rel: `x/${id}` });
  const ids = buildIndex([entry(bmp), entry(astral), entry("a")], "synthetic").entries.map((e) => e.id);
  assert.deepEqual(ids, ["a", bmp, astral], "index order is code point");
});

/* ------------------------------------------------------------------ 3. digest and directory seal vectors */
test("v0.2 artifact digest vectors: exclusions, inclusions, line endings are significant", () => {
  const v = V("digest-seal.json");
  assert.equal(v.digestAlgorithm, DIGEST_ALGORITHM);
  assert.equal(artifactDigest(v.artifact), v.artifactDigest);
  for (const c of v.excludedFieldChanges) assert.equal(artifactDigest(c.artifact), v.artifactDigest, `${c.field} is outside the digest`);
  for (const c of v.includedFieldChanges) { assert.equal(artifactDigest(c.artifact), c.artifactDigest, c.field); assert.notEqual(c.artifactDigest, v.artifactDigest, `${c.field} is inside the digest`); }
});
test("v0.2 directory seal vectors: payload order, mutation, version and registry binding", () => {
  const v = V("digest-seal.json");
  const s = v.seal;
  const r = sealPayload(s.registry, s.id, s.version, s.payload);
  assert.equal(r.seal, s.directorySeal);
  assert.deepEqual(r.payload, s.sortedPayload);
  for (const c of v.sealCases) {
    const got = sealPayload(c.registry ?? s.registry, s.id, c.version ?? s.version, c.payload);
    assert.equal(got.seal, c.seal, c.name);
  }
  assert.equal(v.sealCases[0].seal, s.directorySeal, "reordering the payload keeps the seal");
  assert.ok(v.sealCases.slice(1).every((c) => c.seal !== s.directorySeal), "payload mutation, version, registry change the seal");
});
test("v0.2 fixture golden values: canonical fixture digest/suite digest/seal are unchanged, and carry digestAlgorithm", () => {
  const g = JSON.parse(fs.readFileSync(path.join(PKG_ROOT, "test/golden/digest-seal.json"), "utf8"));
  const r = validateAll();
  const v = r.versions.find((x) => x.rel === g.fixture);
  assert.equal(v.digest, g.artifactDigest);
  assert.equal(v.directorySeal, g.directorySeal);
  assert.equal(g.digestAlgorithm, DIGEST_ALGORITHM);
  assert.equal(YAML.parse(read(PKG_ROOT, `${g.fixture}/release.yaml`)).digestAlgorithm, DIGEST_ALGORITHM);
});

/* ------------------------------------------------------------------ 4. suite-binding vectors */
test("v0.2 suite-binding vectors", () => {
  const v = V("suite-binding.json");
  assert.equal(suiteDigest(v.suite), v.suiteDigest);
  assert.equal(suiteDigest(v.changedSuite), v.changedSuiteDigest);
  for (const c of v.cases) assert.equal(checkSuiteBinding(c.binding, v[c.suite])?.code ?? null, c.expect, c.name);
});
test("v0.2 suite binding in the registry: attestations without registry in the suite block are accepted; suite edit stales; resealing is not enough", () => {
  let root = sandbox();
  mutate(root, `${CAND}/blueprint.yaml`, (d) => { delete d.attestations[0].suite.registry; });
  assert.deepEqual(validateAll({ root }).errors, []);
  root = sandbox();
  mutate(root, `${CAND}/evals/suite.yaml`, (d) => { d.gates.candidate[0].value = 0.01; });
  assert.ok(codes(validateAll({ root })).includes("E_SUITE_STALE"));
  root = sandbox();
  mutate(root, `${CAND}/blueprint.yaml`, (d) => { delete d.attestations[0].suite; });
  assert.ok(codes(validateAll({ root })).includes("E_SCHEMA"), "evaluation attestations require the suite block");
  root = sandbox();
  mutate(root, `${CAND}/blueprint.yaml`, (d) => { d.attestations[0].suite.id = "synthetic.other"; });
  assert.ok(codes(validateAll({ root })).includes("E_SUITE_MISMATCH"));
});

/* ------------------------------------------------------------------ 5. RuntimeLock vectors */
test("v0.2 RuntimeLock vectors: resolution rules, explicit codes, domains", () => {
  const v = V("lock.json");
  for (const c of v.cases) {
    const peers = c.peers ?? v.peers;
    const r = resolveRef(c.requested, peers, { domain: c.domain, allowCandidates: c.allowCandidates });
    assert.equal(r.status, c.expect.status, `${c.name}: ${JSON.stringify(r)}`);
    if (c.expect.status === "resolved") assert.deepEqual([r.resolved.version, r.resolved.digest], [c.expect.version, c.expect.digest], c.name);
    else { assert.equal(r.unresolved.code, c.expect.code, c.name); assert.ok(r.unresolved.message.length > 0, c.name); }
  }
  const lock = buildRuntimeLock(v.subject, v.lock.references, v.peers, { domain: "production" });
  assert.deepEqual(schemaErrors("lock", lock), []);
  assert.deepEqual([lock.complete, lock.entries.length, lock.entries.map((e) => e.status)], [false, 2, ["resolved", "unresolved"]], "every declared reference appears; complete only when all resolve");
  assert.equal(lock.digestAlgorithm, DIGEST_ALGORITHM);
  assert.equal(buildRuntimeLock(v.subject, [v.lock.references[0]], v.peers).complete, true);
  assert.equal(buildRuntimeLock(v.subject, [], v.peers).complete, true, "no references: trivially complete, still a lock");
});

/* ------------------------------------------------------------------ 6. adoption test: peer-index fixtures + exit codes */
test("v0.2 adoption: one real peer-index fixture resolves, one unresolved fixture fails explicitly (exit 0 / exit 1)", () => {
  const root = pkgCopy();
  const ok = cli(root, "resolve.mjs", "synthetic.research-synthesis@1.0.0", "--scope", "synthetic", "--index", path.join(PKG_ROOT, "test/fixtures/peer-index.resolves.synthetic.json"));
  assert.equal(ok.status, 0, ok.stderr);
  const lock = JSON.parse(ok.stdout);
  assert.deepEqual([lock.kind, lock.complete, lock.domain, lock.digestAlgorithm], ["RuntimeLock", true, "synthetic", DIGEST_ALGORITHM]);
  assert.equal(lock.entries.length, 4);
  assert.ok(lock.entries.every((e) => e.status === "resolved"));
  assert.deepEqual(schemaErrors("lock", lock), []);
  const no = cli(root, "resolve.mjs", "synthetic.research-synthesis@1.0.0", "--scope", "synthetic", "--index", path.join(PKG_ROOT, "test/fixtures/peer-index.unresolved.synthetic.json"));
  assert.equal(no.status, 1, "a valid request that cannot be satisfied exits 1");
  const bad = JSON.parse(no.stdout);
  assert.equal(bad.complete, false);
  assert.deepEqual(bad.entries.filter((e) => e.status === "unresolved").map((e) => [e.requested.id, e.unresolved.code]), [["synthetic.fact-checker", "no-satisfying-version"]]);
  const none = cli(root, "resolve.mjs", "synthetic.research-synthesis@1.0.0", "--scope", "synthetic");
  assert.equal(none.status, 1);
  assert.ok(JSON.parse(none.stdout).entries.every((e) => e.unresolved.code === "no-peer-index"));
  // synthetic subject with production-domain peer entries: domains are never mixed
  const prodPeers = path.join(root, "prod-peers.json");
  fs.writeFileSync(prodPeers, JSON.stringify(JSON.parse(fs.readFileSync(path.join(PKG_ROOT, "test/fixtures/peer-index.resolves.synthetic.json"), "utf8")).entries.map((e) => ({ ...e, domain: "production" }))));
  const mixed = cli(root, "resolve.mjs", "synthetic.research-synthesis@1.0.0", "--scope", "synthetic", "--index", prodPeers);
  assert.equal(mixed.status, 1);
  assert.ok(JSON.parse(mixed.stdout).entries.every((e) => e.unresolved.code === "domain-mismatch"));
  // the validator uses the same policy against the same fixtures
  const forQb = (r) => r.errors.filter((e) => e.file.includes("research-synthesis/1.0.0"));
  assert.deepEqual(forQb(validateAll({ root: sandbox(), peerIndexFiles: [path.join(PKG_ROOT, "test/fixtures/peer-index.resolves.synthetic.json")] })), []);
  assert.deepEqual(forQb(validateAll({ root: sandbox(), peerIndexFiles: [path.join(PKG_ROOT, "test/fixtures/peer-index.unresolved.synthetic.json")] })).map((e) => [e.code, e.where]), [["E_UNRESOLVED", "/references/tiny-agents/synthetic.fact-checker"]]);
});
test("v0.2 exit codes: 2 for malformed input and validation errors, 1 for an unsatisfiable valid request, 0 for success", () => {
  const good = pkgCopy();
  assert.equal(cli(good, "validate.mjs").status, 0);
  assert.equal(cli(good, "build-index.mjs").status, 0);
  const bad = pkgCopy();
  write(bad, `${CAND}/evals/suite.yaml`, "x: .inf\n");
  const v = cli(bad, "validate.mjs");
  assert.equal(v.status, 2, v.stdout + v.stderr);
  assert.match(v.stdout, /E_DATA_TYPE/);
  assert.doesNotMatch(v.stdout + v.stderr, /at .*\.mjs|TypeError|Error:/, "diagnostics, not a stack trace");
  assert.equal(cli(bad, "build-index.mjs").status, 2);
  assert.equal(cli(bad, "resolve.mjs", "synthetic.research-synthesis@1.0.0", "--scope", "synthetic").status, 2);
  assert.equal(cli(bad, "seal.mjs", "synthetic.research-synthesis@1.1.0", "--scope", "synthetic").status, 2);
  assert.equal(cli(good, "seal.mjs", "nonsense").status, 2, "usage error");
  assert.equal(cli(good, "resolve.mjs", "synthetic.research-synthesis@1.0.0", "--scope", "synthetic", "--index", path.join(good, "missing.json")).status, 2, "unreadable peer index");
  const malformedPeer = path.join(good, "peer.json");
  fs.writeFileSync(malformedPeer, "{not json");
  assert.equal(cli(good, "resolve.mjs", "synthetic.research-synthesis@1.0.0", "--scope", "synthetic", "--index", malformedPeer).status, 2);
  const errors = [];
  loadPeerIndexes([malformedPeer], errors);
  assert.equal(errors[0].code, "E_PEER_INDEX");
});

/* ------------------------------------------------------------------ 7. non-finite values fail cleanly everywhere */
test("v0.2 regression: non-finite values fail cleanly (controlled diagnostics, exit 2) and never become null or crash", () => {
  const forms = [".inf", "-.inf", ".nan", ".Inf", ".NaN", "+.inf"];
  const files = [[`${CAND}/blueprint.yaml`, "spec.extensions"], [`${CAND}/evals/suite.yaml`, "scenarios"], [`${CAND}/evidence/refs.yaml`, "refs"], [`${CANON}/lifecycle.yaml`, "x"], [`${CANON}/release.yaml`, "x"]];
  for (const form of forms) for (const [rel] of files) {
    const root = sandbox();
    const base = fs.existsSync(path.join(root, rel)) ? read(root, rel) : "";
    write(root, rel, `${base.replace(/\n$/, "")}\nx_nonfinite: ${form}\n`);
    const r = validateAll({ root });
    assert.ok(r.errors.some((e) => e.code === "E_DATA_TYPE" && e.where === "/x_nonfinite"), `${form} in ${rel}: ${JSON.stringify(r.errors.slice(0, 2))}`);
    assert.ok(!codes(r).includes("E_INTERNAL"));
    assert.ok(!r.versions.some((v) => v.rel === rel.split("/").slice(0, -1).join("/").replace(/\/(evals|evidence)$/, "") && v.digest && v.errors.length === 0), "an invalid version is never indexed");
  }
  // programmatic API: never coerced
  const good = parseYaml(read(PKG_ROOT, `${CAND}/blueprint.yaml`));
  const d0 = artifactDigest(good);
  for (const x of [NaN, Infinity, -Infinity]) { const c = structuredClone(good); c.spec.extensions = { x }; assert.throws(() => artifactDigest(c), DataRejectedError); assert.notEqual(d0, "null"); }
  const c = structuredClone(good); c.spec.extensions = { x: null };
  assert.notEqual(artifactDigest(c), d0, "sanity: null is a distinct value");
});

/* ------------------------------------------------------------------ 8. domain isolation */
test("v0.2 domain isolation: synthetic artifacts, evidence and references never enter production", () => {
  // the real registry: production index empty, synthetic index only synthetic entries, every entry carries domain + digestAlgorithm
  const all = validateAll().versions;
  const prod = buildIndex(all, "production"), syn = buildIndex(all, "synthetic");
  assert.deepEqual([prod.entries.length, prod.domain, syn.domain], [0, "production", "synthetic"]);
  assert.ok(syn.entries.length > 0 && syn.entries.every((e) => e.synthetic && e.domain === "synthetic" && e.digestAlgorithm === DIGEST_ALGORITHM && e.id.startsWith("synthetic.")));
  assert.deepEqual(schemaErrors("index", prod), []);
  assert.deepEqual(schemaErrors("index", syn), []);
  assert.ok(schemaErrors("index", { ...prod, entries: syn.entries }).length > 0, "a production index cannot contain synthetic entries");
  assert.ok(schemaErrors("index", { ...syn, entries: prod.entries.concat({ ...syn.entries[0], synthetic: false }) }).length > 0);
  assert.ok(schemaErrors("index", { ...syn, entries: [{ ...syn.entries[0], domain: "production" }] }).length > 0, "entry domain must follow the index domain");
  assert.ok(schemaErrors("index", { ...syn, digestAlgorithm: "other" }).length > 0);
  const { digestAlgorithm, ...noAlg } = syn.entries[0];
  assert.ok(schemaErrors("index", { ...syn, entries: [noAlg] }).length > 0, "entries carry digestAlgorithm");
  // a synthetic artifact moved into the production namespace
  let root = sandbox();
  fs.cpSync(path.join(root, CAND), path.join(root, "qbs/synthetic.research-synthesis/1.1.0"), { recursive: true });
  fs.rmSync(path.join(root, "synthetic/qbs/synthetic.research-synthesis"), { recursive: true });
  fs.rmSync(path.join(root, "synthetic/qbs/synthetic.incident-triage"), { recursive: true });
  assert.ok(codes(validateAll({ root })).includes("E_SYNTHETIC"));
  // production artifact carrying synthetic evidence / a synthetic marker
  root = sandbox();
  const prodDir = "qbs/example.prod-qb/0.1.0";
  fs.cpSync(path.join(root, DRAFT), path.join(root, prodDir), { recursive: true });
  fs.rmSync(path.join(root, "synthetic"), { recursive: true });
  mutate(root, `${prodDir}/blueprint.yaml`, (d) => { d.metadata.id = "example.prod-qb"; d.metadata.synthetic = false; d.metadata.name = "Prod"; });
  assert.ok(codes(validateAll({ root })).includes("E_SYNTHETIC"), "production ids/refs/evidence must not be synthetic: " + JSON.stringify(codes(validateAll({ root }))));
  root = sandbox();
  mutate(root, `${CAND}/evidence/refs.yaml`, (d) => { d.refs[0].synthetic = false; });
  assert.ok(codes(validateAll({ root })).includes("E_SYNTHETIC"));
  // synthetic evidence pointers only inside the synthetic domain
  root = sandbox();
  mutate(root, `${CAND}/evidence/refs.yaml`, (d) => { d.refs[0].uri = "evidence://prod-store/runs/1"; });
  assert.ok(codes(validateAll({ root })).includes("E_SYNTHETIC"));
  // locks never mix domains
  const e = (domain) => ({ registry: "skills", id: "example.skill", version: "1.0.0", maturity: "canonical", lifecycle: "active", digest: "sha256:" + "1".repeat(64), digestAlgorithm: DIGEST_ALGORITHM, domain });
  const ref = { registry: "skills", id: "example.skill", version: "^1.0.0" };
  assert.equal(resolveRef(ref, [e("synthetic")], { domain: "production" }).unresolved.code, "domain-mismatch");
  assert.equal(resolveRef(ref, [e("production")], { domain: "synthetic" }).unresolved.code, "domain-mismatch");
  assert.equal(resolveRef(ref, [e("production"), e("synthetic")], { domain: "production" }).status, "resolved");
});

/* ------------------------------------------------------------------ 9. hashed contract surfaces carry digestAlgorithm; filesystem hygiene */
test("v0.2 digestAlgorithm is required wherever a digest is carried (release, digest-pinned reference, index, lock)", () => {
  let root = sandbox();
  mutate(root, `${CANON}/release.yaml`, (d) => { delete d.digestAlgorithm; });
  assert.ok(codes(validateAll({ root })).includes("E_SCHEMA"));
  root = sandbox();
  mutate(root, `${CANON}/release.yaml`, (d) => { d.digestAlgorithm = "zeptly-jcs-v2"; });
  assert.ok(validateAll({ root }).errors.some((e) => e.file.endsWith("release.yaml")));
  root = sandbox();
  mutate(root, `${DRAFT}/blueprint.yaml`, (d) => { d.references[0].digest = "sha256:" + "a".repeat(64); });
  assert.ok(codes(validateAll({ root })).includes("E_SCHEMA"), "a digest-pinned reference needs digestAlgorithm");
  root = sandbox();
  mutate(root, `${DRAFT}/blueprint.yaml`, (d) => { d.references[0].digest = "sha256:" + "a".repeat(64); d.references[0].digestAlgorithm = DIGEST_ALGORITHM; });
  assert.ok(!codes(validateAll({ root })).includes("E_SCHEMA"));
  root = sandbox();
  mutate(root, `${CANON}/blueprint.yaml`, (d) => { d.metadata.origin.evolution = undefined; delete d.metadata.origin.evolution; });
  assert.ok(!codes(validateAll({ root })).includes("E_SCHEMA"));
});
test("v0.2 filesystem hygiene: FIFOs and case-colliding paths are rejected before hashing", () => {
  let root = sandbox();
  execFileSync("mkfifo", [path.join(root, CAND, "evidence", "pipe")]);
  let r = validateAll({ root });
  assert.ok(r.errors.some((e) => e.code === "E_SPECIAL_FILE" && e.file.endsWith("evidence/pipe")), JSON.stringify(r.errors.slice(0, 3)));
  root = sandbox();
  fs.writeFileSync(path.join(root, CAND, "Blueprint.yaml"), "a: 1\n");
  r = validateAll({ root });
  assert.ok(r.errors.some((e) => e.code === "E_CASE_COLLISION"));
  root = sandbox();
  fs.mkdirSync(path.join(root, "synthetic/qbs/Synthetic.research-synthesis"));
  assert.ok(validateAll({ root }).errors.some((e) => e.code === "E_CASE_COLLISION" && e.file.startsWith("synthetic/qbs/")), "sibling directories that differ only by case");
});
